version: "2"

services:
  api:
    build: ./api
    environment:
      - DEVELOPMENT=true
      - GOPORT=5000
      - REDIS_CACHE_DURATION=3600
    ports:
      - 5000
    links:
      - redis
  redis:
    image: redis
    ports:
      - 5044:6379
  kongfig:
    build: ./kongfigure
    environment:
      - KONG_API_NAME=surgeons-local
      - API_VIRTUAL_HOST=surgeons.arthrex.xyz
      - KONG_HOST=kong.arthrex.xyz:8001
      - KONG_KEY
      - KONG_CERT
      - KONG_SECRET_TEST
    links:
      - api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  dev:
    external:
      name: arthrex_dev
